<script lang="ts">
	interface PlaylistTrack {
		mbid: string;
		title: string;
		artist: string;
		album?: string;
		position: number;
		reason: string;
		flowRole: 'opener' | 'builder' | 'peak' | 'valley' | 'closer' | 'transition';
		similarityScore: number;
		category: 'popular' | 'deep-cut' | 'hidden-gem';
		tags: Array<{ name: string }>;
	}

	interface Props {
		seedTrack: {
			title: string;
			artist: string;
		};
		playlist: PlaylistTrack[];
	}

	let { seedTrack, playlist }: Props = $props();

	let viewMode = $state<'visual' | 'json' | 'markdown'>('visual');
	let expandedTrack = $state<number | null>(null);

	function toggleExpand(position: number) {
		expandedTrack = expandedTrack === position ? null : position;
	}

	function getFlowRoleEmoji(role: string): string {
		switch (role) {
			case 'opener':
				return '🎬';
			case 'builder':
				return '📈';
			case 'peak':
				return '⚡';
			case 'valley':
				return '🌙';
			case 'closer':
				return '🌅';
			case 'transition':
				return '🔄';
			default:
				return '🎵';
		}
	}

	function getCategoryBadge(category: string): { label: string; class: string } {
		switch (category) {
			case 'popular':
				return { label: 'Popular', class: 'badge-popular' };
			case 'deep-cut':
				return { label: 'Deep Cut', class: 'badge-deep' };
			case 'hidden-gem':
				return { label: 'Hidden Gem', class: 'badge-gem' };
			default:
				return { label: '', class: '' };
		}
	}

	function generateMarkdown(): string {
		let md = `# Playlist inspired by "${seedTrack.title}" by ${seedTrack.artist}\n\n`;
		md += `Generated by GroveMusic\n\n`;
		md += `---\n\n`;

		for (const track of playlist) {
			md += `## ${track.position}. ${track.title}\n`;
			md += `**${track.artist}**`;
			if (track.album) md += ` — *${track.album}*`;
			md += `\n\n`;
			md += `> ${track.reason}\n\n`;
			if (track.tags.length > 0) {
				md += `Tags: ${track.tags.slice(0, 5).map((t) => `\`${t.name}\``).join(', ')}\n\n`;
			}
			md += `---\n\n`;
		}

		return md;
	}

	function copyToClipboard(text: string) {
		navigator.clipboard.writeText(text);
	}
</script>

<div class="playlist-view">
	<div class="playlist-header">
		<h2>Your Playlist</h2>
		<p class="seed-info">
			Inspired by "<strong>{seedTrack.title}</strong>" by {seedTrack.artist}
		</p>

		<div class="view-toggle">
			<button
				class:active={viewMode === 'visual'}
				onclick={() => (viewMode = 'visual')}
			>
				Visual
			</button>
			<button
				class:active={viewMode === 'json'}
				onclick={() => (viewMode = 'json')}
			>
				JSON
			</button>
			<button
				class:active={viewMode === 'markdown'}
				onclick={() => (viewMode = 'markdown')}
			>
				Markdown
			</button>
		</div>
	</div>

	{#if viewMode === 'visual'}
		<div class="track-list">
			{#each playlist as track}
				<div
					class="track-card"
					class:expanded={expandedTrack === track.position}
					onclick={() => toggleExpand(track.position)}
					onkeydown={(e) => e.key === 'Enter' && toggleExpand(track.position)}
					tabindex="0"
					role="button"
				>
					<div class="track-main">
						<span class="track-position">{track.position}</span>
						<span class="track-flow">{getFlowRoleEmoji(track.flowRole)}</span>
						<div class="track-info">
							<span class="track-title">{track.title}</span>
							<span class="track-artist">{track.artist}</span>
						</div>
						<span class="track-score">{track.similarityScore}/10</span>
						<span class="badge {getCategoryBadge(track.category).class}">
							{getCategoryBadge(track.category).label}
						</span>
					</div>

					{#if expandedTrack === track.position}
						<div class="track-details">
							<p class="track-reason">{track.reason}</p>
							{#if track.album}
								<p class="track-album">Album: <em>{track.album}</em></p>
							{/if}
							{#if track.tags.length > 0}
								<div class="track-tags">
									{#each track.tags.slice(0, 5) as tag}
										<span class="tag">{tag.name}</span>
									{/each}
								</div>
							{/if}
						</div>
					{/if}
				</div>
			{/each}
		</div>
	{:else if viewMode === 'json'}
		<div class="code-view">
			<button class="copy-button" onclick={() => copyToClipboard(JSON.stringify(playlist, null, 2))}>
				Copy JSON
			</button>
			<pre><code>{JSON.stringify(playlist, null, 2)}</code></pre>
		</div>
	{:else}
		<div class="code-view">
			<button class="copy-button" onclick={() => copyToClipboard(generateMarkdown())}>
				Copy Markdown
			</button>
			<pre><code>{generateMarkdown()}</code></pre>
		</div>
	{/if}
</div>

<style>
	.playlist-view {
		max-width: 800px;
		margin: 0 auto;
	}

	.playlist-header {
		text-align: center;
		margin-bottom: 2rem;
	}

	.playlist-header h2 {
		margin: 0 0 0.5rem;
		color: #e0e0e0;
	}

	.seed-info {
		color: #888;
		margin-bottom: 1rem;
	}

	.view-toggle {
		display: flex;
		gap: 0.5rem;
		justify-content: center;
	}

	.view-toggle button {
		padding: 0.5rem 1rem;
		border: 1px solid #3a3a4a;
		border-radius: 4px;
		background: #1a1a2e;
		color: #888;
		cursor: pointer;
		transition: all 0.2s;
	}

	.view-toggle button:hover,
	.view-toggle button.active {
		background: #2d2d5a;
		color: #e0e0e0;
		border-color: #6366f1;
	}

	.track-list {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.track-card {
		background: #1a1a2e;
		border: 1px solid #3a3a4a;
		border-radius: 8px;
		cursor: pointer;
		transition: all 0.2s;
	}

	.track-card:hover {
		border-color: #6366f1;
	}

	.track-card.expanded {
		border-color: #6366f1;
		background: #1e1e3a;
	}

	.track-main {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		padding: 0.75rem 1rem;
	}

	.track-position {
		width: 2rem;
		text-align: center;
		font-weight: bold;
		color: #6366f1;
	}

	.track-flow {
		font-size: 1.25rem;
	}

	.track-info {
		flex: 1;
		min-width: 0;
	}

	.track-title {
		display: block;
		font-weight: 500;
		color: #e0e0e0;
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}

	.track-artist {
		display: block;
		font-size: 0.85rem;
		color: #888;
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}

	.track-score {
		font-weight: 500;
		color: #4ade80;
	}

	.badge {
		padding: 0.25rem 0.5rem;
		font-size: 0.7rem;
		font-weight: 600;
		text-transform: uppercase;
		border-radius: 4px;
	}

	.badge-popular {
		background: #3b82f6;
		color: white;
	}

	.badge-deep {
		background: #8b5cf6;
		color: white;
	}

	.badge-gem {
		background: #f59e0b;
		color: white;
	}

	.track-details {
		padding: 0 1rem 1rem;
		border-top: 1px solid #3a3a4a;
		margin-top: 0.5rem;
		padding-top: 0.75rem;
	}

	.track-reason {
		color: #b0b0b0;
		font-style: italic;
		margin: 0 0 0.5rem;
	}

	.track-album {
		color: #888;
		font-size: 0.9rem;
		margin: 0 0 0.5rem;
	}

	.track-tags {
		display: flex;
		flex-wrap: wrap;
		gap: 0.25rem;
	}

	.tag {
		padding: 0.125rem 0.375rem;
		font-size: 0.75rem;
		background: #2a2a4a;
		color: #a5b4fc;
		border-radius: 4px;
	}

	.code-view {
		position: relative;
	}

	.copy-button {
		position: absolute;
		top: 0.5rem;
		right: 0.5rem;
		padding: 0.5rem 1rem;
		background: #6366f1;
		color: white;
		border: none;
		border-radius: 4px;
		cursor: pointer;
		font-size: 0.85rem;
	}

	.copy-button:hover {
		background: #4f46e5;
	}

	pre {
		background: #0d0d1a;
		padding: 1rem;
		border-radius: 8px;
		overflow-x: auto;
		max-height: 500px;
	}

	code {
		font-family: 'JetBrains Mono', 'Fira Code', monospace;
		font-size: 0.85rem;
		color: #e0e0e0;
	}
</style>
